### ISSUE TITLE
Empty output directories

### ISSUE THREAD

**Issue by haesleinhuepf** [campaslab/STRESS#1]
On Windows, there is a scenario where the `output/` folder remains empty when running `AnalyzeDeluxe3D.m`. In the MATLAB output, there is this error message:
```
Traceback (most recent call last): 
  File "Call_Me_At_The_End.py", line 17, in <module> 
    BDCA.Load_Dict_From_Matfile(test_matfile_file_path) 
  File "C:\Users\Administrator\Desktop\STRESS-main\STRESS-main\Batch_Droplet_Class_Analysis.py", line 54, in Load_Dict_From_Matfile 
    Batch_Droplet_Class_Analysis(Loaded_Dict) 
  File "C:\Users\Administrator\Desktop\STRESS-main\STRESS-main\Batch_Droplet_Class_Analysis.py", line 94, in __init__ 
    for index, file in enumerate(sorted(os.listdir(str(directory).replace("\\","/")))): 
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/Username/Desktop/STRESS-main/STRESS-main/Short_ExampleTifSequence-InteriorLabel-vsx_2.076um-vsz_3.998um-TimeInterval_3.00min-21timesteps-1_analyzed_2022_6_13_18_25/seg3DResults-Quick Edge Detection - Parallelized/CoordsAndCurves_2022_6_13_18_25' 
```

This error is related to this: https://stackoverflow.com/questions/19187812/os-listdir-cant-see-my-directory

**Comment by haesleinhuepf** [comment]
The issue was related to the file name of the example dataset being to long. I propose to rename [`ExampleTifSequence-InteriorLabel-vsx_2.076um-vsz_3.998um-TimeInterval_3.00min-21timesteps.tif`](https://github.com/campaslab/STRESS/blob/main/ExampleTifSequence-InteriorLabel-vsx_2.076um-vsz_3.998um-TimeInterval_3.00min-21timesteps.tif) to `example.tif`. Then it will work.
